### ISSUE TITLE
Storing and Event Marker to the recording

### ISSUE THREAD

**Issue by hcuve** [seemoo-lab/pyshimmer#14]
Hi, thanks for the great work with this API.

We are trying to integrate shimmer with a Psychopy https://www.psychopy.org/ experiment where we present some images and want to record the physiological signals using the shimmer kit.

Is there a way to send a "trigger"/ event marker using the API, such that I can synchronise the image presentation with the recording afterwards?

I hope this makes sense

**Comment by lumagi** [comment]
I'm not sure I understand correctly. You would like to insert some kind of a marker / data point into a Shimmer recording by sending a Bluetooth command?

**Comment by lumagi** [comment]
That's interesting, I hadn't seen that slide before. But are you certain that this functionality that Consensys offers does a round-trip to the Shimmer device? Judging from the slides, it might just store those events locally on the computer and correlate it with the measurement once the Shimmer has completed its recording.

I also took a look into the header file of the Shimmer3 firmware that lists all available Shimmer Bluetooth commands. I didn't find anything that could be related to such a feature. Maybe you also want to give it a go:
https://github.com/ShimmerResearch/shimmer3/blob/master/LogAndStream/shimmer3_common_source/Bluetooth_SD/shimmer_bt_comms.h

But would you be opposed to doing the synchronization on the host instead of on the Shimmer? You could stream the measurement timestamps to the host over Bluetooth and store the timestamp along with the events that occur on the host computer. Once the recording on the Shimmer is completed, you can correlate the events based on the common timestamp.

**Comment by hcuve** [comment]
Thanks for the response, you are probably right that it is a consensys feature and not the shimmer device.

I think your suggestion would work as well, do you have any pointers on how to execute this?

**Comment by lumagi** [comment]
You could basically adapt the Bluetooth example in the README. The code starts data streaming from the Shimmer to the host. The `handler` function is then called periodically to receive a new data packet from the Shimmer. You can extract the timestamp from the `pkt`.

```python
import time
from serial import Serial

from pyshimmer import ShimmerBluetooth, DEFAULT_BAUDRATE, DataPacket, EChannelType


def handler(pkt: DataPacket) -> None:
    timestamp = pkt[EChannelType.TIMESTAMP]
    # Do something with the timestamp


if __name__ == '__main__':
    serial = Serial('/dev/rfcomm42', DEFAULT_BAUDRATE)
    shim_dev = ShimmerBluetooth(serial)

    shim_dev.initialize()

    dev_name = shim_dev.get_device_name()
    print(f'My name is: {dev_name}')

    shim_dev.add_stream_callback(handler)

    shim_dev.start_streaming()
    time.sleep(5.0)
    shim_dev.stop_streaming()

    shim_dev.shutdown()
```

**Comment by hcuve** [comment]
Thank you, appreciate it!

**Comment by lumagi** [comment]
I'm closing this for now. If you're having any more issues with the examples, feel free to reopen.
